services:
  web:
    image: kanekojosiah/nextjs-week10-app:local
    container_name: nextjs-week10-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped